kettings/urls.py
from django.urls import path

from kettings import views

app_name = 'kettings'


urlpatterns = [
    path('editor/st-<int:site_pk>/ct-<int:content_type_pk>/oi-<int:object_pk>/',
         views.SettingsEditorView.as_view(), name='settings_editor'),

    path('editor/st-<int:site_pk>/ct-<int:content_type_pk>/oi-<int:object_pk>/',
         views.SettingsEditorView.as_view(), name='settings_editor'),
    path('manager/st-<int:site_pk>/ct-<int:content_type_pk>/oi-<int:object_pk>/cf-<int:vform_pk>/',
         views.SettingsEditorView.as_view(), name='settings_editor'),

    path('viewer/st-<int:site_pk>/ct-<int:content_type_pk>/oi-<int:object_pk>/',
         views.SettingsViewerView.as_view(), name='settings_viewer'),
    path('viewer/st-<int:site_pk>/ct-<int:content_type_pk>/oi-<int:object_pk>/cf-<int:vform_pk>/',
         views.SettingsViewerView.as_view(), name='settings_viewer'),
]

kettings/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from mptt.models import MPTTModel, TreeForeignKey
from mptt.managers import TreeManager


class Group(MPTTModel, models.Model):
    name = models.CharField(max_length=100)
    label = models.CharField(max_length=100, null=True, blank=True)
    type = models.CharField(max_length=50)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', on_delete=models.CASCADE)
    description = models.CharField(max_length=100, null=True, blank=True)
    sort = models.PositiveIntegerField(default=1000)
    cls_path = models.CharField(max_length=250, null=True, blank=True)
    is_active = models.BooleanField(default=False)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)

    tree = TreeManager()
    objects = models.Manager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('type', 'sort', 'name',)

    class MPTTMeta:
        order_insertion_by = ['sort']

    def get_label(self):
        return self.label or self.name

    def get_active_children(self):
        return self.children.filter(is_active=True)


class Setting(models.Model):
    site = models.ForeignKey('sites.Site', on_delete=models.CASCADE, related_name='%(app_label)s%(class)s_site')
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    key = models.CharField(max_length=255)
    value = models.TextField()
    is_active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    sort = models.PositiveIntegerField(default=1000)

    object_id = models.PositiveIntegerField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    content_object = GenericForeignKey()

    def __str__(self):
        return '%s: %s' % (self.key, self.value)

    class Meta:
        ordering = ('sort', 'group', 'key',)
        unique_together = ('site', 'key', 'content_type', 'object_id', 'group')

kettings/forms.py
from django import forms

kettings/views.py
from django.contrib.sites.models import Site
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.shortcuts import get_object_or_404
from django import forms

from kettings.registry.settings.editor import SettingEditorUtils
from kettings.registry.settings.viewer import SettingViewerUtils
from kettings.registry.constants import KettingsK
from kettings.models import Group, Setting


class SettingsBase(TemplateView):
    site = None
    vform = None
    content_object = None
    ctn_type = None  # TemplateView already has attr named 'content_type'
    object = None

    def dispatch(self, request, *args, **kwargs):
        SettingEditorUtils().refresh_settings()

        self.site = get_object_or_404(Site, pk=self.kwargs['site_pk'])
        self.ctn_type = get_object_or_404(ContentType, pk=self.kwargs['content_type_pk'])
        self.vform = self.get_vform()
        self.content_object = self.get_content_object()
        return super(SettingsBase, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(SettingsBase, self).get_context_data(**kwargs)

        context.update({
            'vgroups': self.get_vgroups(),
            'vform': self.vform,
            'site': self.site,
            'content_type': self.ctn_type,
            'object_pk': self.kwargs['object_pk']
        })

        return context

    def get_vgroups(self):
        return Group.objects.filter(is_active=True, type=KettingsK.GRP_TYPE_VGROUP.value, content_type=self.ctn_type)

    def get_vform(self):
        all_vforms = Group.objects.filter(is_active=True, type=KettingsK.GRP_TYPE_VFORM.value)
        vform_pk = self.kwargs.get('vform_pk', None)
        if vform_pk:
            all_vforms = all_vforms.filter(pk=vform_pk)

        return all_vforms.first()

    def get_content_object(self):
        return get_object_or_404(self.ctn_type.model_class(), pk=self.kwargs['object_pk'])


class SettingsEditorView(FormView, SettingsBase):
    template_name = 'kettings/settings_editor.html'

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw['request'] = self.request
        kw['content_object'] = self.content_object
        return kw

    def get_initial(self):
        initial = super(SettingsEditorView, self).get_initial()

        qs = Setting.objects.filter(
            site=self.site,
            group=self.vform
        ).values('key', 'value')

        dt = {x['key']: x['value'] for x in qs}
        initial.update(dt)

        return initial

    def form_valid(self, form):
        if self.vform:

            for key, val in form.cleaned_data.items():
                vfield = form.fields[key]

                val = vfield.pre_save(key, val, form, self.vform)
                val = val or ''

                setting = Setting.objects.update_or_create(
                    site=self.site,
                    group=self.vform,
                    key=key,
                    object_id=self.kwargs['object_pk'],
                    content_type=self.ctn_type,
                    defaults={
                        'value': val,
                    })[0]

                vfield.post_save(key, val, form, self.vform, setting)

            messages.success(self.request, 'Updated settings successfully')
            self.success_url = self.request.get_full_path()

        return super(SettingsEditorView, self).form_valid(form)

    def get_form_class(self):
        form_class = None

        if self.vform:
            form_class = SettingEditorUtils().import_form(self.vform)

        if not form_class:
            class DummyForm(forms.Form):
                pass
            form_class = DummyForm

        return form_class


class SettingsViewerView(SettingsBase):
    template_name = 'kettings/settings_viewer.html'

    def get_settings_values(self):
        set_viewer = SettingViewerUtils(self.site, self.content_object)

        return set_viewer.get_values(self.vform.parent.cls_path, self.vform.cls_path)
        # res1 = set_viewer.get_value(self.vform.parent.cls_path, self.vform.cls_path, 'app_name')

    def get_context_data(self, **kwargs):
        context = super(SettingsViewerView, self).get_context_data(**kwargs)

        context.update({
            'values': self.get_settings_values(),
        })

        return context

kettings/templates/kettings/base.html
{% block content %}
{% endblock %}

{% block static_js %}
{% endblock %}

{% block static_css %}
{% endblock %}

kettings/templates/kettings/settings_editor.html
{% extends 'kettings/base.html' %}

{% block title %}{{ vform.get_label }} | Settings{% endblock %}

{% block static_css %}
	{{ super.block }}

	{{ form.media }}
{% endblock %}

{% block pretitle %}
	<h5 class="mb-0 small">{{ site.domain }}</h5>
	<h3>Settings for {{ vform.get_label }}</h3>
{% endblock %}


{% block content %}

	<div class="row">
		<div class="col-md-2">
			{% for grp0 in vgroups %}
			<table class="module table table-bordered w-100 bg-white">
				<thead>
					<tr>
						<th>{{ grp0.get_label }}</th>
					</tr>
				</thead>
				<tbody>
				{% for grp1 in grp0.get_active_children %}
					<tr>
						<td>
							<a href='{% url "kettings:settings_editor" site.pk content_type.pk object_pk grp1.pk %}'>
								{{ grp1.get_label }}
							</a>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
			{% endfor %}
		</div>

		<div class="col-md-10">

			<form method="post" action="." {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
				{% csrf_token %}

				<table class="table table-bordered bg-white shadow-sm">
					<thead>
						<tr>
							<th>Field</th>
							<th>Value</th>
						</tr>
					</thead>
					<tbody>
						{{ form }}
					</tbody>

					<tfoot>
						<tr>
							<td></td>
							<td>
								<input type="submit" value="Save" class="default" />
							</td>
						</tr>
					</tfoot>

				</table>

			</form>
		</div>
	</div>

{% endblock %}

kettings/templates/kettings/settings_viewer.html
{% extends 'admin/base_site.html' %}

{% block title %}{{ vform.get_label }} | Settings{% endblock %}

{% block extrastyle %}
	{{ super.block }}
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

{% endblock %}

{% block pretitle %}
	<h5 class="mb-0 small">{{ site.domain }}</h5>
	<h3>Settings for {{ vform.get_label }}</h3>
{% endblock %}


{% block content %}
	<div class="row">
		<div class="col-md-2">
			{% for grp0 in vgroups %}
			<table class="module table table-bordered w-100">
				<thead>
					<tr>
						<th>{{ grp0.get_label }}</th>
					</tr>
				</thead>
				<tbody>
				{% for grp1 in grp0.get_active_children %}
					<tr>
						<td>
							<a href='{% url "kettings:settings_viewer" site.pk content_type.pk object_pk grp1.pk %}'>
								{{ grp1.get_label }}
							</a>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
			{% endfor %}
		</div>

		<div class="col-md-10">

				<table class="table table-bordered">
					<thead>
						<tr>
							<th>Field</th>
							<th>Value</th>
						</tr>
					</thead>
					<tbody>
						{% for val in values %}
							<tr>
								<td>{{ val.key }}</td>
								<td>{{ val.value }}</td>
							</tr>
						{% endfor %}
					</tbody>

				</table>

		</div>
	</div>

{% endblock %}